# Generated by Django 4.1.5 on 2023-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Įveskite automobilio markę(pvz. Audi)', max_length=80, verbose_name='Automobilio markė')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį(pvz. 100)', max_length=80, verbose_name='Automobilio markė')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilio modeliai',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įveskite valstybinį nr: ', max_length=10, verbose_name='Valstybiniai numeriai')),
                ('vin_kodas', models.CharField(help_text='Įveskite VIN kodą: ', max_length=17, verbose_name='VIN kodas')),
                ('klientas', models.CharField(help_text='Įveskite klientą: ', max_length=80, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.automobiliomodelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite suteiktos paslaugos pavadinimą: ', max_length=100, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.FloatField(max_length=20, verbose_name='Paslaugos kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, help_text='Užsakymo data?', max_length=20, verbose_name='Data')),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisas.automobilis')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(max_length=20, verbose_name='Kiekis')),
                ('paslauga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eilutes', to='servisas.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymo eilutės',
            },
        ),
    ]
