# Generated by Django 4.1.5 on 2023-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kiekis',
            field=models.IntegerField(verbose_name='Kiekis'),
        ),
    ]
