# Generated by Django 4.1.5 on 2023-01-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0002_alter_uzsakymo_eilute_kiekis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='marke',
            field=models.CharField(help_text='Įveskite automobilio markę', max_length=80, verbose_name='Automobilio markė'),
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='modelis',
            field=models.CharField(help_text='Įveskite automobilio modelį', max_length=80, verbose_name='Automobilio modelis'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='klientas',
            field=models.CharField(help_text='Įveskite vardą ', max_length=80, verbose_name='Klientas'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(help_text='Įveskite valstybinį numerį ', max_length=10, verbose_name='Valstybiniai numeriai'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='vin_kodas',
            field=models.CharField(help_text='Įveskite 17 skaitmenų kodą ', max_length=17, verbose_name='VIN kodas'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='pavadinimas',
            field=models.CharField(help_text='Įveskite paslaugos pavadinimą ', max_length=100, verbose_name='Paslaugos pavadinimas'),
        ),
    ]
