# Generated by Django 4.1.5 on 2023-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0005_automobilis_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='virselis',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
