# Generated by Django 4.1.5 on 2023-01-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0009_remove_uzsakymas_due_back_uzsakymas_terminas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grąžinti iki:'),
        ),
    ]
