# Generated by Django 4.1.5 on 2023-01-25 12:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0010_alter_uzsakymas_terminas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
    ]
