# Generated by Django 4.1.5 on 2023-01-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0012_uzsakymoapzvalga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='uzsakymas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atsiliepimai', to='servisas.uzsakymas'),
        ),
    ]
