# Generated by Django 4.1.5 on 2023-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0013_alter_uzsakymoapzvalga_uzsakymas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data'),
        ),
    ]
