# Generated by Django 4.1.5 on 2023-01-27 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servisas', '0015_alter_uzsakymoapzvalga_uzsakymas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='klientas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vartotojas', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
