# Generated by Django 4.1.5 on 2023-01-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0016_alter_uzsakymoapzvalga_klientas_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzsakymoapzvalga',
            old_name='uzsakymas_id',
            new_name='uzsakymas',
        ),
        migrations.RenameField(
            model_name='uzsakymoapzvalga',
            old_name='klientas_id',
            new_name='vartotojas',
        ),
    ]
