# Generated by Django 4.1.5 on 2023-01-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servisas', '0017_rename_uzsakymas_id_uzsakymoapzvalga_uzsakymas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='uzsakymas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atsiliepimai', to='servisas.uzsakymas', verbose_name='Užsakymas'),
        ),
        migrations.CreateModel(
            name='Profilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
