# Generated by Django 4.1.5 on 2023-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0018_alter_uzsakymoapzvalga_uzsakymas_profilis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilis',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
