# Generated by Django 4.1.5 on 2023-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0019_alter_profilis_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilis',
            name='foto',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
