# Generated by Django 4.1.5 on 2023-01-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0021_alter_profilis_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
    ]
