# Generated by Django 4.1.5 on 2023-02-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servisas', '0022_alter_profilis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymo_eilute',
            options={'verbose_name': 'Orderline', 'verbose_name_plural': 'Orderlines'},
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='kaina',
            field=models.FloatField(max_length=20, verbose_name='Service cost'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='pavadinimas',
            field=models.CharField(help_text='Įveskite paslaugos pavadinimą ', max_length=100, verbose_name='Service title'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.automobilis', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateTimeField(auto_now_add=True, help_text='Užsakymo data?', max_length=20, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Confirmed'), ('v', 'In Progress'), ('a', 'Cancelled'), ('i', 'Done')], default='p', help_text='Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due back:'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kiekis',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='paslauga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.paslauga', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='uzsakymas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eilutes', to='servisas.uzsakymas', verbose_name='Order'),
        ),
    ]
