# Generated by Django 4.1.5 on 2023-02-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servisas', '0023_alter_paslauga_options_alter_uzsakymas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiliomodelis',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoapzvalga',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='marke',
            field=models.CharField(help_text='Įveskite automobilio markę', max_length=80, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='modelis',
            field=models.CharField(help_text='Įveskite automobilio modelį', max_length=80, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='profilis',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profilis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='uzsakymas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atsiliepimai', to='servisas.uzsakymas', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='uzsakymoapzvalga',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vartotojas', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
